# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_management
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: